name: Octo Organization CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ exec-workflow ]
    branches: master
env:
  ADMIN: Kumar
  CITY: Pune
 
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Printing variable here
      run: echo ${{ env.ADMIN }}

  CD:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set variable here
      run: echo ${{ env.CITY }}
    env:
      key1: ${{ env.CITY }}
