name: Octo Organization CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ exec-workflow ]
    branches: master

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set-Up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Compile Code
      run: mvn clean compile
