name: Octo Organization CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ exec-workflow ]
    branches: master
 
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set variable here
      run: echo Setting Variables here
      env:
        ADMIN: Kumar
        CITY: Pune
  CD:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set variable here
      run: echo ${{ jobs.CI.steps.env.ADMIN }}
