name: Octo Organization CI

on: |
  [push]
  repository_dispatch:
    types: [ exec-workflow ]
    branches: ${{ github.event.client_payload.branch }}

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
