name: Octo Organization CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ exec-workflow ]
    branches: master

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
